---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
    - name: MY_ENV_VAR
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: MY_ENV_VAR
